/**
 * Database seed script. Run with `npm run db:seed`.
 * Idempotent — safe to run multiple times against the same database.
 */
import "dotenv/config";
import { PrismaClient, Prisma } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const ROLES = [
  { name: "ADMIN" as const, description: "Full platform access: user management, all content, analytics." },
  { name: "TEACHER" as const, description: "Can upload documents, generate questions/exams, view analytics for own content." },
  { name: "STUDENT" as const, description: "Can view assigned documents, take exams, browse the question bank." },
];

const SEED_USERS = [
  {
    email: "admin@eduai.local",
    password: "Admin123!",
    firstName: "Ava",
    lastName: "Administrator",
    roles: ["ADMIN"],
  },
  {
    email: "teacher@eduai.local",
    password: "Teacher123!",
    firstName: "Tom",
    lastName: "Teacher",
    roles: ["TEACHER"],
  },
  {
    email: "student@eduai.local",
    password: "Student123!",
    firstName: "Sam",
    lastName: "Student",
    roles: ["STUDENT"],
  },
];

const SAMPLE_QUESTIONS = [
  {
    type: "MULTIPLE_CHOICE" as const,
    difficulty: "EASY" as const,
    prompt: "What is the powerhouse of the cell?",
    options: [
      { key: "A", text: "Nucleus" },
      { key: "B", text: "Mitochondria" },
      { key: "C", text: "Ribosome" },
      { key: "D", text: "Golgi apparatus" },
    ],
    correctAnswer: "B",
    explanation: "Mitochondria generate most of the cell's ATP through cellular respiration.",
    tags: ["biology", "cells"],
  },
  {
    type: "TRUE_FALSE" as const,
    difficulty: "EASY" as const,
    prompt: "The mitochondria has its own DNA, separate from the cell's nuclear DNA.",
    options: [
      { key: "True", text: "True" },
      { key: "False", text: "False" },
    ],
    correctAnswer: "True",
    explanation: "Mitochondrial DNA (mtDNA) is inherited maternally and is distinct from nuclear DNA.",
    tags: ["biology", "genetics"],
  },
  {
    type: "MULTIPLE_CHOICE" as const,
    difficulty: "MEDIUM" as const,
    prompt: "Which pigment absorbs light most strongly in the blue and red portions of the spectrum?",
    options: [
      { key: "A", text: "Melanin" },
      { key: "B", text: "Keratin" },
      { key: "C", text: "Chlorophyll" },
      { key: "D", text: "Hemoglobin" },
    ],
    correctAnswer: "C",
    explanation: "Chlorophyll reflects green light, which is why plants appear green.",
    tags: ["biology", "photosynthesis"],
  },
  {
    type: "SHORT_ANSWER" as const,
    difficulty: "MEDIUM" as const,
    prompt: "Name the two main stages of cellular respiration that occur after glycolysis.",
    options: null,
    correctAnswer: "The Krebs cycle and the electron transport chain.",
    explanation: null,
    tags: ["biology", "respiration"],
  },
  {
    type: "FILL_IN_BLANK" as const,
    difficulty: "EASY" as const,
    prompt: "Glycolysis splits one molecule of glucose into two molecules of _____.",
    options: null,
    correctAnswer: "pyruvate",
    explanation: null,
    tags: ["biology", "respiration"],
  },
  {
    type: "MULTIPLE_CHOICE" as const,
    difficulty: "HARD" as const,
    prompt: "Which process directly uses the proton gradient generated by the electron transport chain?",
    options: [
      { key: "A", text: "Glycolysis" },
      { key: "B", text: "Chemiosmosis (ATP synthase)" },
      { key: "C", text: "The Calvin cycle" },
      { key: "D", text: "Transcription" },
    ],
    correctAnswer: "B",
    explanation: "ATP synthase uses the proton gradient to phosphorylate ADP into ATP — a process called chemiosmosis.",
    tags: ["biology", "respiration"],
  },
  {
    type: "ESSAY" as const,
    difficulty: "HARD" as const,
    prompt: "Compare and contrast photosynthesis and cellular respiration in terms of inputs, outputs, and location within the cell.",
    options: null,
    correctAnswer:
      "A strong answer covers: photosynthesis converts CO2 + water + light energy into glucose + oxygen in the chloroplast; " +
      "respiration converts glucose + oxygen into CO2 + water + ATP in the mitochondria; the two processes are " +
      "complementary, with the outputs of one serving as inputs to the other.",
    explanation: null,
    tags: ["biology", "photosynthesis", "respiration"],
  },
  {
    type: "SHORT_ANSWER" as const,
    difficulty: "EASY" as const,
    prompt: "What gas do plants release as a byproduct of photosynthesis?",
    options: null,
    correctAnswer: "Oxygen",
    explanation: null,
    tags: ["biology", "photosynthesis"],
  },
];

async function main() {
  console.log("Seeding roles...");
  for (const role of ROLES) {
    await prisma.role.upsert({
      where: { name: role.name },
      update: { description: role.description },
      create: role,
    });
  }

  console.log("Seeding users...");
  const userIdByEmail = new Map<string, string>();
  for (const seedUser of SEED_USERS) {
    const passwordHash = await bcrypt.hash(seedUser.password, 12);
    const roles = await prisma.role.findMany({ where: { name: { in: seedUser.roles as ("ADMIN" | "TEACHER" | "STUDENT")[] } } });

    const user = await prisma.user.upsert({
      where: { email: seedUser.email },
      update: {},
      create: {
        email: seedUser.email,
        passwordHash,
        firstName: seedUser.firstName,
        lastName: seedUser.lastName,
        roles: { create: roles.map((role) => ({ roleId: role.id })) },
      },
    });
    userIdByEmail.set(seedUser.email, user.id);
    console.log(`  - ${user.email} (${seedUser.roles.join(", ")})`);
  }

  const teacherId = userIdByEmail.get("teacher@eduai.local")!;

  console.log("Seeding sample question bank...");
  const existingSampleQuestions = await prisma.question.findMany({
    where: { createdById: teacherId, tags: { has: "biology" } },
  });

  let sampleQuestions = existingSampleQuestions;
  if (existingSampleQuestions.length === 0) {
    await prisma.question.createMany({
      data: SAMPLE_QUESTIONS.map((q) => ({
        ...q,
        options: q.options ?? Prisma.JsonNull,
        documentId: null,
        chunkId: null,
        createdById: teacherId,
        model: null,
      })),
    });
    sampleQuestions = await prisma.question.findMany({
      where: { createdById: teacherId, tags: { has: "biology" } },
      orderBy: { createdAt: "asc" },
    });
    console.log(`  - created ${sampleQuestions.length} sample questions`);
  } else {
    console.log(`  - ${existingSampleQuestions.length} sample questions already exist, skipping`);
  }

  console.log("Seeding a sample published exam...");
  const existingExam = await prisma.exam.findFirst({ where: { title: "Biology Basics: Cells & Energy" } });
  if (!existingExam && sampleQuestions.length > 0) {
    await prisma.exam.create({
      data: {
        createdById: teacherId,
        title: "Biology Basics: Cells & Energy",
        description: "A short sample quiz covering cellular respiration and photosynthesis fundamentals.",
        status: "PUBLISHED",
        durationMinutes: 20,
        passingScore: 60,
        examQuestions: {
          create: sampleQuestions.map((q, index) => ({ questionId: q.id, order: index + 1, points: 1 })),
        },
      },
    });
    console.log("  - created and published 'Biology Basics: Cells & Energy'");
  } else {
    console.log("  - sample exam already exists, skipping");
  }

  console.log("\nSeed complete. Demo credentials:");
  for (const u of SEED_USERS) {
    console.log(`  ${u.email} / ${u.password}`);
  }
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
